chromosomes:
  - NC_058189.1
  - NC_058190.1
  - NC_058191.1
  - NC_058192.1
  - NC_058193.1
  - NC_058194.1
  - NC_058195.1
  - NC_058196.1
  - NC_058197.1
  - NC_058198.1

chrom_lengths:
  NC_058189.1: 71177040
  NC_058190.1: 54650663
  NC_058191.1: 43944265
  NC_058192.1: 41442133
  NC_058193.1: 40263884
  NC_058194.1: 34462492
  NC_058195.1: 34009066
  NC_058196.1: 33488718
  NC_058197.1: 20753350
  NC_058198.1: 24000787

roh_parameters:
  min_kb: 1000
  window_snp: 500
  window_het: 2 
  window_missing: 2

final_output:
 - results/froh/merged_froh.tsv
